name: LiveControl
version: '1.0'
main: io.cj_cate.github.liveControl.Main
api-version: '1.21'

commands:
  livecontrol:
    description: Main command for LiveControl server management.
  lc:
    description: Alias for livecontrol


permissions:
  livecontrol.admin:
    description: Gives access to all LiveControl commands.